### ISSUE TITLE
Wildcard certs from public CA's

### ISSUE THREAD

**Issue by djzort** [floragunncom/search-guard-ssl-docs#3]
Is it possible to use wildcard certificates from public CA's on the REST/SSL side?

**Comment by floragunncom** [comment]
Of course. All you need is to transform you certificate into JKS (with java keytool) or PCKS12 (with openssl or java keytool). 

Generate a PKCS12 keystore from PEM files:
```openssl pkcs12 -export -in fullchain.pem -inkey privkey.pem -out keystore.p12 -name myalias -CAfile chain.pem -caname root -password pass:XXX```

Generate a JKS keystore from a PKCS12 keystore (optional):
```keytool -importkeystore -srcstorepass XXX -deststorepass changeit -destkeypass changeit -srckeystore keystore.p12 -srcstoretype PKCS12 -alias myalias -keystore keystore.jks
keytool -import -trustcacerts -alias root -deststorepass changeit -file chain.pem -noprompt -keystore keystore.jks```

**Comment by djzort** [comment]
Ok i get this:

```
[2016-06-27 18:13:41,444][INFO ][com.floragunn.searchguard.ssl.SearchGuardKeyStore] Open SSL not available (this is not an error, we simply fallback to built-in JDK SSL) because of java.lang.ClassNotFoundException: org.apache.tomcat.jni.SSL
[2016-06-27 18:13:41,446][INFO ][com.floragunn.searchguard.ssl.SearchGuardKeyStore] Open SSL not available (this is not an error, we simply fallback to built-in JDK SSL) because of java.lang.ClassNotFoundException: org.apache.tomcat.jni.SSL
[2016-06-27 18:13:42,137][INFO ][com.floragunn.searchguard.ssl.SearchGuardKeyStore] Config directory is /etc/elasticsearch/, from there the key- and truststore files are resolved relatively
[2016-06-27 18:13:42,257][INFO ][com.floragunn.searchguard.ssl.SearchGuardKeyStore] Transport keystore subject DN no. 0 CN=xxxxx.our.domain, OU=SSL, O=Test, L=Test, C=DE
[2016-06-27 18:13:42,259][INFO ][com.floragunn.searchguard.ssl.SearchGuardKeyStore] Transport keystore subject DN no. 1 CN=XXXXXX, OU=XXXXXX, O=XXXXXX, DC=XXXXXXX, DC=com.au
[2016-06-27 18:13:42,259][INFO ][com.floragunn.searchguard.ssl.SearchGuardKeyStore] Transport keystore subject DN no. 2 CN=XXXXXXX, OU=XXXXXX, O=XXXXXX, DC=XXXXX, DC=com.au
[2016-06-27 18:13:42,259][INFO ][com.floragunn.searchguard.ssl.SearchGuardKeyStore] Transport keystore subject DN no. 3 CN=XXXXXXXXXXXXXX, OU=SSL, O=Test, L=Test, C=DE
[2016-06-27 18:13:42,390][INFO ][com.floragunn.searchguard.ssl.SearchGuardKeyStore] HTTPS client auth mode OPTIONAL
[2016-06-27 18:13:42,580][INFO ][com.floragunn.searchguard.ssl.SearchGuardKeyStore] HTTP keystore subject DN no. 0 CN=*.our.domain, OU=XXXXXXX, O=XXXXXXX, L=XXXXXX, ST=New South Wales, C=AU
[2016-06-27 18:13:42,581][INFO ][com.floragunn.searchguard.ssl.SearchGuardKeyStore] HTTP keystore subject DN no. 1 CN=XXXXXXXx OU=XXXXXX, O=XXXXXXXX, ST=New South Wales, C=AU
[2016-06-27 18:13:42,581][INFO ][com.floragunn.searchguard.ssl.SearchGuardKeyStore] HTTP keystore subject DN no. 2 CN=*.our.domain, OU=XXXXXXXXXXX, O=XXXXXX, L=XXXXXXX, ST=New South Wales, C=AU
[2016-06-27 18:13:42,735][ERROR][bootstrap                ] Exception
ElasticsearchSecurityException[java.io.IOException: Keystore was tampered with, or password was incorrect]; nested: IOException[Keystore was tampered with, or password was incorrect]; nested: UnrecoverableKeyException[Password verification failed];
	at com.floragunn.searchguard.ssl.SearchGuardKeyStore.initSSLConfig(SearchGuardKeyStore.java:358)
	at com.floragunn.searchguard.ssl.SearchGuardKeyStore.<init>(SearchGuardKeyStore.java:139)
	at com.floragunn.searchguard.ssl.SearchGuardSSLModule.<init>(SearchGuardSSLModule.java:29)
	at com.floragunn.searchguard.ssl.SearchGuardSSLPlugin.nodeModules(SearchGuardSSLPlugin.java:127)
	at org.elasticsearch.plugins.PluginsService.nodeModules(PluginsService.java:263)
	at org.elasticsearch.node.Node.<init>(Node.java:179)
	at org.elasticsearch.node.Node.<init>(Node.java:140)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Caused by: java.io.IOException: Keystore was tampered with, or password was incorrect
	at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:780)
	at sun.security.provider.JavaKeyStore$JKS.engineLoad(JavaKeyStore.java:56)
	at sun.security.provider.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:224)
	at sun.security.provider.JavaKeyStore$DualFormatJKS.engineLoad(JavaKeyStore.java:70)
	at java.security.KeyStore.load(KeyStore.java:1445)
	at com.floragunn.searchguard.ssl.SearchGuardKeyStore.initSSLConfig(SearchGuardKeyStore.java:341)
	... 10 more
Caused by: java.security.UnrecoverableKeyException: Password verification failed
	at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:778)
	... 15 more

```

**Comment by djzort** [comment]
```
### Search Guard
## Transport layer SSL
searchguard.ssl.transport.enabled: true
searchguard.ssl.transport.keystore_type: JKS
searchguard.ssl.transport.keystore_filepath: transport_keystore.jks
#searchguard.ssl.transport.keystore_alias: my_alias
searchguard.ssl.transport.keystore_password: xxxxx
searchguard.ssl.transport.truststore_type: JKS
searchguard.ssl.transport.truststore_filepath: transport_truststore.jks
#searchguard.ssl.transport.truststore_alias: my_alias
searchguard.ssl.transport.truststore_password: xxxx
searchguard.ssl.transport.enforce_hostname_verification: true
searchguard.ssl.transport.resolve_hostname: true
searchguard.ssl.transport.enable_openssl_if_available: true

## HTTP/REST layer SSL
searchguard.ssl.http.enabled: true
searchguard.ssl.http.keystore_type: PKCS12
searchguard.ssl.http.keystore_filepath: keystore_kttps.p12
#searchguard.ssl.http.keystore_alias: my_alias
searchguard.ssl.http.keystore_password: xxxx
#searchguard.ssl.http.truststore_type: JKS
searchguard.ssl.http.truststore_filepath: truststore_https.jks
#searchguard.ssl.http.truststore_alias: my_alias
searchguard.ssl.http.truststore_password: xxxxx
searchguard.ssl.http.enable_openssl_if_available: true
searchguard.ssl.http.clientauth_mode: OPTIONAL
```

**Comment by djzort** [comment]
its telling me theres a keystore error, having opened the keystore...

**Comment by floragunncom** [comment]
The ```Keystore was tampered with, or password was incorrect``` exception is caused because you supplied a wrong HTTP truststorepassword -> ```searchguard.ssl.http.truststore_password```

**Comment by djzort** [comment]
thanks!
