### ISSUE TITLE
ES is down after installing Search Guard

### ISSUE THREAD

**Issue by iqbal-nazir** [floragunncom/search-guard-ssl-docs#4]
Hello,
I was following your [tutorial](https://github.com/floragunncom/search-guard-ssl-docs/blob/a8f61fbc181b0f44a2f2c3d7946d2950b649b06e/quickstart.md) to add Search Guard SSL plugin with my ELK server. But after 'Configurating HTTPS' my ELK got down. If I check /var/log/ELK.log, I see the following:

```
[2016-06-29 11:13:38,247][WARN ][com.floragunn.searchguard.ssl.http.netty.SearchGuardSSLNettyHttpServerTransport] [ELK_1st_node] Someone speaks plaintext instead of ssl, will close the channel
[2016-06-29 11:13:38,249][ERROR][watcher.input.http       ] [ELK_1st_node] failed to execute [http] input for [org.elasticsearch.watcher.watch.Watch@5efed351]
java.net.SocketException: Unexpected end of file from server
        at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:792)
        at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)
        at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:789)
        at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1536)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
        at org.elasticsearch.watcher.support.http.HttpClient.doExecute(HttpClient.java:204)
        at org.elasticsearch.watcher.support.http.HttpClient.execute(HttpClient.java:125)
        at org.elasticsearch.watcher.input.http.ExecutableHttpInput.doExecute(ExecutableHttpInput.java:64)
        at org.elasticsearch.watcher.input.http.ExecutableHttpInput.execute(ExecutableHttpInput.java:56)
        at org.elasticsearch.watcher.input.http.ExecutableHttpInput.execute(ExecutableHttpInput.java:40)
        at org.elasticsearch.watcher.execution.ExecutionService.executeInner(ExecutionService.java:357)
        at org.elasticsearch.watcher.execution.ExecutionService.execute(ExecutionService.java:273)
        at org.elasticsearch.watcher.execution.ExecutionService$WatchExecutionTask.run(ExecutionService.java:438)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[2016-06-29 11:13:39,661][WARN ][com.floragunn.searchguard.ssl.http.netty.SearchGuardSSLNettyHttpServerTransport] [ELK_1st_node] Someone speaks plaintext instead of ssl, will close the channel
[2016-06-29 11:13:42,169][WARN ][com.floragunn.searchguard.ssl.http.netty.SearchGuardSSLNettyHttpServerTransport] [ELK_1st_node] Someone speaks plaintext instead of ssl, will close the channel

```

Can you please help me solve this?

**Comment by floragunncom** [comment]
Please have a look at this log message on top of your stacktrace:

[2016-06-29 11:13:38,247][WARN ][com.floragunn.searchguard.ssl.http.netty.SearchGuardSSLNettyHttpServerTransport] [ELK_1st_node] Someone speaks plaintext instead of ssl, will close the channel

"Someone speaks plaintext instead of ssl, will close the channel" is the key here. If you configured SSL on the REST layer (i.e. HTTPS), only HTTPS requests are allowed. Plain HTTP requests will be dropped.

It seems the HTTP request stems from Watcher. While we do not support Watcher officially at the moment, I guess that configuring Watcher to use HTTPS instead of HTTP is similar to configuring Kibana. You can read about Kibana integration here:

https://github.com/floragunncom/search-guard-docs/blob/master/kibana.md

Please refer to the Watcher HTTP input documentation to figure out how to configure HTTPS:

https://www.elastic.co/guide/en/watcher/current/input.html#input-http

I guess you'll have to adjust this setting:

request.scheme
"Url scheme. Valid values are: http or https"

Please let us know if this works.

**Comment by iqbal-nazir** [comment]
Thanks for your reply.
After your reply I understood that I have to integrate SG SSL with Kibana. Then I was following the given URL. There I am having few problems:

- I don't find `root-ca.pem` file. So I set `elasticsearch.ssl.verify: false`
- I don't find `sg_roles.yml`file too.

and in terms of Watcher, I am not getting exactly where I should add `request.scheme`

**Comment by floragunncom** [comment]
* If you need only SSL and not authentication or authorization then you don't need ``sg_roles.yml``
* ``root-ca.pem`` is under ``example-pki-scripts/ca``
* Regarding Watcher pls ask your questions here https://discuss.elastic.co/c/watcher

**Comment by floragunncom** [comment]
No response, assume solved. If its not solved for you pls. ask question on google groups https://groups.google.com/forum/#!forum/search-guard or create an issue here https://github.com/floragunncom/search-guard-ssl
